In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# importamos el Dataset
import pandas as pd

# Al estar en la misma carpeta, solo necesitamos el nombre
path_local = "earthquakes.csv"

try:
    # Cargamos directamente el archivo local
    # Recuerda mantener sep=';' si ese es el formato de tu archivo
    df = pd.read_csv(path_local, sep=';')
    
    # Aplicamos tus mejoras de estilo
    pd.set_option('display.max_columns', None)
    
    print("¡Archivo local cargado con éxito!")
    print(df.head())
    
except FileNotFoundError:
    print("Error: No encontré el archivo. Asegúrate de haberlo subido al entorno.")

¡Archivo local cargado con éxito!
  usgs_id,date,year,month,lat,lon,depth_km,magnitude,mag_type,magnitude_class,location_desc,review_status,n_stations,azimuthal_gap,min_station_dist,rms
0  cent19000105190000000,1900-01-05,1900,1,-3.0,1...
1  cent19000111090700000,1900-01-11,1900,1,-5.0,1...
2  cent19000120063300000,1900-01-20,1900,1,20.0,-...
3  cent19000131192200000,1900-01-31,1900,1,48.0,1...
4  ushis389,1900-04-30,1900,4,36.9,-121.6,,4.5,ml...

In [3]:
# 1. Cargamos el archivo asegurando que el separador sea la coma
# Si lo subiste manualmente usa el nombre del archivo, si no, la URL completa
df = pd.read_csv('earthquakes.csv', sep=',')

# 2. Configuración para que la tabla se vea estética y completa
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)


df.head()

                 usgs_id        date  year  month   lat    lon  depth_km  magnitude mag_type   magnitude_class                location_desc review_status  n_stations  azimuthal_gap  min_station_dist  rms
0  cent19000105190000000  1900-01-05  1900      1  -3.0  102.0       NaN        7.0       ms    Major (M7-7.9)  Southern Sumatra, Indonesia      reviewed         NaN            NaN               NaN  NaN
1  cent19000111090700000  1900-01-11  1900      1  -5.0  148.0       NaN        7.0       ms    Major (M7-7.9)                 Bismarck Sea      reviewed         NaN            NaN               NaN  NaN
2  cent19000120063300000  1900-01-20  1900      1  20.0 -105.0       NaN        7.3       mw    Major (M7-7.9)              Jalisco, Mexico      reviewed         NaN            NaN               NaN  NaN
3  cent19000131192200000  1900-01-31  1900      1  48.0  146.0     450.0        7.5       mj    Major (M7-7.9)               Sea of Okhotsk      reviewed         NaN            NaN               NaN  NaN
4               ushis389  1900-04-30  1900      4  36.9 -121.6       NaN        4.5       ml  Light (M4.5-4.9)      Near Aromas, California      reviewed         NaN            NaN               NaN  NaN

In [4]:
dfshape = df.shape
print(f"El dataset tiene {dfshape[0]} filas y {dfshape[1]} columnas.")

El dataset tiene 230805 filas y 16 columnas.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 230805 entries, 0 to 230804
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   usgs_id           230805 non-null  str
 1   date              230805 non-null  str
 2   year              230805 non-null  int64
 3   month             230805 non-null  int64
 4   lat               230805 non-null  float64
 5   lon               230805 non-null  float64
 6   depth_km          230068 non-null  float64
 7   magnitude         230805 non-null  float64
 8   mag_type          230804 non-null  str
 9   magnitude_class   230805 non-null  str
 10  location_desc     230805 non-null  str
 11  review_status     230805 non-null  str
 12  n_stations        79682 non-null   float64
 13  azimuthal_gap     101621 non-null  float64
 14  min_station_dist  62282 non-null   float64
 15  rms               183332 non-null  float64
dtypes: float64(8), int64(2), str(6)
memory usage: 28.2 MB

In [6]:
print(df.isnull().sum())
df.head()

usgs_id                  0
date                     0
year                     0
month                    0
lat                      0
lon                      0
depth_km               737
magnitude                0
mag_type                 1
magnitude_class          0
location_desc            0
review_status            0
n_stations          151123
azimuthal_gap       129184
min_station_dist    168523
rms                  47473
dtype: int64

                 usgs_id        date  year  month   lat    lon  depth_km  magnitude mag_type   magnitude_class                location_desc review_status  n_stations  azimuthal_gap  min_station_dist  rms
0  cent19000105190000000  1900-01-05  1900      1  -3.0  102.0       NaN        7.0       ms    Major (M7-7.9)  Southern Sumatra, Indonesia      reviewed         NaN            NaN               NaN  NaN
1  cent19000111090700000  1900-01-11  1900      1  -5.0  148.0       NaN        7.0       ms    Major (M7-7.9)                 Bismarck Sea      reviewed         NaN            NaN               NaN  NaN
2  cent19000120063300000  1900-01-20  1900      1  20.0 -105.0       NaN        7.3       mw    Major (M7-7.9)              Jalisco, Mexico      reviewed         NaN            NaN               NaN  NaN
3  cent19000131192200000  1900-01-31  1900      1  48.0  146.0     450.0        7.5       mj    Major (M7-7.9)               Sea of Okhotsk      reviewed         NaN            NaN               NaN  NaN
4               ushis389  1900-04-30  1900      4  36.9 -121.6       NaN        4.5       ml  Light (M4.5-4.9)      Near Aromas, California      reviewed         NaN            NaN               NaN  NaN

In [7]:
# Sobrescribimos la variable original para que el dataset ya no tenga nulos
df = df.dropna()

# Ahora puedes comprobarlo directamente en la variable de siempre:
print(df.isnull().sum())

usgs_id             0
date                0
year                0
month               0
lat                 0
lon                 0
depth_km            0
magnitude           0
mag_type            0
magnitude_class     0
location_desc       0
review_status       0
n_stations          0
azimuthal_gap       0
min_station_dist    0
rms                 0
dtype: int64

In [11]:
df['magnitude_class'].info()

<class 'pandas.Series'>
Index: 31073 entries, 3963 to 230804
Series name: magnitude_class
Non-Null Count  Dtype
--------------  -----
31073 non-null  str
dtypes: str(1)
memory usage: 485.5 KB

In [10]:
df['magnitude_class'].value_counts()

magnitude_class
Light (M4.5-4.9)     23626
Moderate (M5-5.9)     6901
Strong (M6-6.9)        485
Major (M7-7.9)          60
Great (M8+)              1
Name: count, dtype: int64

In [26]:
# 2. Lista de columnas a eliminar (incluyendo las técnicas y las que causaban error)
columnas_a_eliminar = ['date', 'year', 'month', 'mag_type', 'magnitude_class',
    'location_desc', 'review_status', 'n_stations', 'azimuthal_gap', 
    'min_station_dist', 'rms'
]
df = df.drop(columns=columnas_a_eliminar, errors='ignore')

# 5. Eliminar duplicados si los hay
df = df.drop_duplicates()

# 6. Guardar el archivo definitivo para los modelos
df.to_csv('dataset_earthquake_final.csv', index=False)

print("✅ Archivo 'dataset_earthquake_final.csv' creado con éxito.")
print(f"📊 Shape final: {df.shape}")
print(f"📋 Columnas resultantes: {list(df.columns)}")
# 6. Guardar el archivo definitivo
df.to_csv('dataset_earthquake_final.csv', index=False)

print(f"✅ Archivo 'dataset_earthquake_final.csv' creado con éxito.")
print(f"📏 Shape final: {df.shape}")
print(f"📊 Columnas resultantes: {list(df.columns)}")

✅ Archivo 'dataset_earthquake_final.csv' creado con éxito.
📊 Shape final: (31073, 6)
📋 Columnas resultantes: ['usgs_id', 'lat', 'lon', 'depth_km', 'magnitude', 'severity']
✅ Archivo 'dataset_earthquake_final.csv' creado con éxito.
📏 Shape final: (31073, 6)
📊 Columnas resultantes: ['usgs_id', 'lat', 'lon', 'depth_km', 'magnitude', 'severity']

In [27]:
# 4. Crear nuestra propia columna categórica limpia (Target)
# Evitamos el "Other" agrupando los datos directamente desde la magnitud numérica
# Clase 0: Moderado (4.5 a 5.9) -> Incluye el 'Light' y 'Moderate' original
# Clase 1: Severo / Fuerte (>= 6.0)
limites_magnitud = [4.4, 5.9, 10.0]
nombres_clases = [0, 1] 

df['severity'] = pd.cut(df['magnitude'], bins=limites_magnitud, labels=nombres_clases)

print("\nDistribución de la nueva variable 'severity':")
print(df['severity'].value_counts())

Distribución de la nueva variable 'severity':
severity
0    30523
1      549
Name: count, dtype: int64

In [25]:
# Supongamos que predecimos una categoría de magnitud basada en variables numéricas
X = df[['lat', 'lon', 'depth_km']]